// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkfvyojblkfrnsicdabp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprZnZ5b2pibGtmcm5zaWNkYWJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MTQzNTEsImV4cCI6MjA1ODE5MDM1MX0.EFCDH0CL6FOG2m46woykhY1siSyHwsEFMofKvLTEztI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);